### ISSUE TITLE
PSR15 middleware support

### ISSUE THREAD

**Issue by fetchandadd** [franzliedke/whoops-middleware#6]
I am interested in support for PSR15 middleware. 

Despite the fact that PSR 15 is not yet finished I already started on an approach to support version `^0.4`.

Have a look at timtegeler/whoops-middleware@47c18c1ca85b2bc9b5ad4d14c2f2d8146fb9e800

Perhaps you can review my approach and share your thoughts with me. :)

**Comment by franzliedke** [comment]
Hi Tim, thanks for getting in touch! :)

Your commit looks like a good start, I will be happy about a PR. 

I've been out of the loop a little bit, so I have a quick question about PSR-15: Is that going to be the "official" standard, or did the http-interop project take over because the PSR did not pass the standardization process?

**Comment by fetchandadd** [comment]
Nice. I will provide a PR soon. :)

About your question: In my understanding the http-interop is the "official" PSR-15 project. At least,  @shadowhand, the Editor of PSR-15 (http://www.php-fig.org/psr/) is the main contributor of http-interop/http-middleware.

**Comment by shadowhand** [comment]
PSR-15 is expected to enter the review period soon.

**Comment by franzliedke** [comment]
This is now released in [version 0.5.0](https://github.com/franzliedke/whoops-middleware/releases/tag/0.5.0).
